### ISSUE TITLE
split project into go and python repository and deprecate this repository

### ISSUE THREAD

**Issue by mfs12** [Duet3D/DSF-APIs#6]
To ease handling with repos, issues, tags and more it is helpful to split this project into

- DSF-API-go
- DSF-API-python

**Comment by mfs12** [comment]
>  consider there are links to the current repository from lots of forum posts and the documentation.

**Comment by mfs12** [comment]
- create new repos, one for go, one for python
- add links to new repos and a comment about what happend in the readme file here
- archive or set project read-only

**Comment by wilriker** [comment]
Mind that for Go the GitHub URL is used in dependency management. So if you move away the Go library from this repo users will have to actively change their dependencies.

**Comment by mfs12** [comment]
I totally agree. this can upset users. And this should be avoid. We should think about how to communicate this as good as possible. 

Is it possible to add a deprecation warning with a custom message in go or python?

**Comment by wilriker** [comment]
> Is it possible to add a deprecation warning with a custom message in go or python?

I don't know about python but there is no such thing for Go. You have to rely on the user of the library realizing that there are no more updates or seeing the announcement in the forum or reading the deprecation notice in this repository. Also in case of moving a Go library to a new package you would have to create a new Go module from that, so effectively the user has to switch to that module then.

**Comment by mfs12** [comment]
https://github.com/golang/go/wiki/Deprecated

**Comment by mfs12** [comment]
Python has a deprecation warning... https://docs.python.org/3/library/warnings.html

**Comment by mfs12** [comment]
Rename projects into:

- dsf-go
- dsf-python

**Comment by mfs12** [comment]
- DONE created dsf-python repo https://github.com/Duet3D/dsf-python
- DONE created dsf-go repo https://github.com/Duet3D/dsf-go
- DONE renamed dsf-python package
- DONE renamed dsf-go package
- DONE created pull request with python deprecation exception
- DONE created pull request with go deprecation text (no warning or exception is possible, but added a deprection text to each package containing a link to the new repo.
- pull requests need merge...
