### ISSUE TITLE
Create deb package for godsfapi

### ISSUE THREAD

**Issue by mfs12** [Duet3D/DSF-APIs#8]
Having an available easy to install and update package allows user to use this functionality quicker and might make it more popular.

**Comment by wilriker** [comment]
This is completely against Go development workflow and no Go developer will use it as it would be much more complicated to use a locally installed dependency than using the (versioned) sources directly from GitHub.

**Comment by mfs12** [comment]
This task doesn't make sense, because go installs modules via git urls.

Thanks for clarification, @wilriker
